### PR TITLE
Better downloaded dependency detection.

### PR DESCRIPTION
**Pull request by calavera**
Woow, sorry about breaking everything! This PR fixes the build again.

/cc @d2fn

### CODE REVIEW

**Comment by d2fn** [comment]
lol https://travis-ci.org/d2fn/gopack/jobs/15607192

**Comment by calavera** [comment]
gosh, why is travis not building my PRs??!!!

**Comment by d2fn** [comment]
```
The authenticity of host 'github.com (192.30.252.130)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
```

https://travis-ci.org/d2fn/gopack/jobs/15607192#L83

not sure what's going on

**Comment by calavera** [comment]
I've removed that ssh connection at https://github.com/d2fn/gopack/pull/54

**Pull request merged**
