### PR TITLE
Add `installdeps` command.

### PR DESCRIPTION
**Pull request by calavera**
So you can do `./gp installdeps` rather than:

```
GOPATH="`pwd`/.gopack/vendor" go install \
  github.com/bmizerany/assert            \
  github.com/ParsePlatform/go.grace      \
  github.com/technoweenie/grohl          \
  ...
```

/cc @d2fn, @technoweenie

### CODE REVIEW

**Comment by technoweenie** [comment]
Awesome :+1:

**Comment by calavera** [comment]
mmm unfortunately I think this implementation has some issues. Taking a look

**Comment by calavera** [comment]
I've made the code more simple to run `go install` for each import and it looks like it works better now. Unfortunately we've lost the two tests cases, although the new code is really easy to understand. The command is still fast enough, this is timing `go-octokit`:

```
calavera@dcp ~/oss/go-octokit (use_gopack●)$ time bin/gp-darwin-amd64 installdeps
/// g o p a c k ///
updating code.google.com/p/go-netrc/netrc
pointing code.google.com/p/go-netrc/netrc at commit 0da3cb9c37e0
updating github.com/lostisland/go-sawyer
pointing github.com/lostisland/go-sawyer at commit ec1b99a1915d53f09d40d0c87caf60460b7f8728
updating github.com/jtacoma/uritemplates
pointing github.com/jtacoma/uritemplates at commit 2b6fc855d3a722bc0e5525ae50bb3c10703c5450
updating github.com/bmizerany/assert
pointing github.com/bmizerany/assert at commit e17e99893cb6509f428e1728281c2ad60a6b31e3
updating github.com/bmizerany/assert
pointing github.com/bmizerany/assert at commit e17e99893cb6509f428e1728281c2ad60a6b31e3
bin/gp-darwin-amd64 installdeps  0.57s user 0.42s system 22% cpu 4.324 total
calavera@dcp ~/oss/go-octokit (use_gopack●)$
```

**Comment by calavera** [comment]
@d2fn this is ready to merge, what do you think?

**Comment by d2fn** [comment]
:thumbsup:

**Pull request merged**
